services:
  backend:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads
      - ./jobs:/app/jobs
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    restart: unless-stopped

volumes:
  uploads:
  downloads:
  jobs: